### ISSUE TITLE
Query parameters cannot be parsed out of the box

### ISSUE THREAD

**Issue by ahmedhammad97** [aaronwlee/Attain#1]
In express for example, a route like `/hello?name=JohnSmith`, can be parsed using `req.query` to get an object `{name: "JohnSmith"}`.

I can't find anything similar in Attain. I am aware of the `parser` plugin, but it only parses the body.

**Comment by aaronwlee** [comment]
@ahmedhammad97 Thanks for letting me know a good point. I've updated this function. Now you can use it :). Just make sure you've reloaded all the modules.
