### ISSUE TITLE
Is it possible to add session for requests?

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#10]
We also need session middleware like exspres-session for identify all request, do you have any ideas?

**Comment by Coteh** [comment]
I was taking a look at this earlier: https://github.com/denjucks/session

Would this be compatible with Attain?

**Comment by aaronwlee** [comment]
https://github.com/denjucks/session/pull/2
I already make a supporting middleware and waiting for merging it. Please bear with me :)

**Comment by aaronwlee** [comment]
@devalexqt @Coteh  Good news! now we can use it https://deno.land/x/session

**Comment by devalexqt** [comment]
Very nice!

**Comment by Coteh** [comment]
Awesome! 👍

**Comment by devalexqt** [comment]
To get session id  from req: `req.session.sessionId`
