### ISSUE TITLE
Please add options to disable header "x-powered-by: Deno.js, Attain v0.5"

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#12]
How to hide this header?
```
x-powered-by: Deno.js, Attain v0.5
```

**Comment by aaronwlee** [comment]
@devalexqt I don't want to remove x-powered-by
Instead of adding an option, can you use it?
```ts
app.use((req, res) => {
  console.log(res.headers.delete("x-powered-by"));
})
```

**Comment by devalexqt** [comment]
But this is another middleware in stack  :( and will be cool if just set options in `app.listen({ port: 8000, ... })`

**Comment by aaronwlee** [comment]
I've updated a security middleware, it's not only removing x-powered-by but also adding some useful headers.
https://github.com/aaronwlee/Attain#security-options

**Comment by devalexqt** [comment]
Thanks! It's awesome!
