### ISSUE TITLE
Query params returns non-empty object on URL without query params

### ISSUE THREAD

**Issue by burhanahmeed** [aaronwlee/Attain#2]
Hi, It's cool framework!

I recently create a web boilerplate with Attain, I find something weird behavior on `req.query`.
In ExpressJS when I have URL without query params, it returns empty object `{}` on `console.log(req.query)`.
I try using Attain and it returns `{ : "" }` on `console.log(req.query)`. I am afraid if someone might need to check whether the url has query params using `Object.keys(req.query).length` it will return an error.
I don't know the best way to check query params exist or not besides using `Object.keys(req.query).length` or is there any plan to make kind of query params checker?

**Comment by aaronwlee** [comment]
Thanks for letting me know the bug. I presume it should not return the empty object if search params are empty. It must not return this `{ : "" }`.
I've applied harder restrictions on the creation and saving the parsed data. Now, the parser returns undefined when the parsed data is empty.

ex) /hello => If the search param is empty.
`req.query ` is undefined

ex) /hello?name=
`
req.query = {
  name: ""
}
`

ex) /hello?name=Aaron
`
req.query = {
  name: "Aaron"
}
`

**Comment by burhanahmeed** [comment]
Great! It works
