### ISSUE TITLE
TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by marisaoliva** [aaronwlee/Attain#25]
Hello
I try to do a simple exercise with deno and Attain and I've had this error

`error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.50.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.50.0/path/posix.ts:433:18

Found 2 errors.`

Mi code is this:

`import { App } from 'https://deno.land/x/attain/mod.ts';

const app = new App();

app.listen( {
  port: 3000
})

console.log('server running localhost:3000')`

I don't understand what happens, Is possible a global error?

Thanks!

**Comment by aaronwlee** [comment]
@marisaoliva Hi thanks for leaving a comment.
It is definitely related to this [issue](https://github.com/denoland/deno/issues/5365)

I've updated the new version for supporting it.

you can re-try after `deno run --reload https://deno.land/x/attain/mod.ts` or use `import {} from "https://deno.land/x/attain@0.9.5/mod.ts"`

**Comment by marisaoliva** [comment]
Thank you so muchs!! :)
