### ISSUE TITLE
TS2345 error while trying to run the cli

### ISSUE THREAD

**Issue by itays123** [aaronwlee/Attain#26]
Hello there!
I was trying to run your CLI with the command you put in your repo:
`$ deno install -A -f --unstable -n attain https://deno.land/x/attain@1.0.5/attain-cli.ts `

when I did, deno cached all of the dependencies and then outputted this error:
`error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
        sorted: true,
        ~~~~~~~~~~~~
    at https://deno.land/std@v0.61.0/testing/asserts.ts:26:9`

are you familiar with this problem? I also tried to run v1.0.0 but it outputted the same problem again.

**Comment by aaronwlee** [comment]
Which deno version are you using?

**Comment by itays123** [comment]
deno 1.1.2

**Comment by aaronwlee** [comment]
hum. I think the 0.6x.x deno standard libraries are required to use up to deno 1.2.x version. this might be a problem.
