### ISSUE TITLE
anything else to do before 1.1.0?

### ISSUE THREAD

**Issue by itays123** [aaronwlee/Attain#34]
If there is anything I can do I'll be happy to help.

**Comment by aaronwlee** [comment]
@itays123 hum... actually, I'd like to update the performance benchmark because it's been outdated. Now, it's way faster than Deno 1.0.x version. If you know anything about server benchmarking tools, please let me know.

**Comment by itays123** [comment]
@aaronwlee Not really actually but from what I've seen in this benchmark you need to build the same server with the same performance with Attain, Express and Oak and compare how much time it takes... But It's probably more complicated that that isn't it?
