### ISSUE TITLE
HTTPS is supported?

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#8]
Is it https is supported for creating server?

**Comment by aaronwlee** [comment]
Yet to support it. I currently use the Nginx for the https management due to the fact that I've been using it as a microservice.

If you need to release a product with stand-alone service with deno, then I can immediately support that.

I'll keep an eye on it someone really needs it. Let me know.

**Comment by devalexqt** [comment]
I need htts for deno. ;)

**Comment by aaronwlee** [comment]
@devalexqt https://github.com/aaronwlee/Attain/blob/master/README.md#app check this out

you can simply use 0.4 version branch to reload the attain modules

**Comment by devalexqt** [comment]
Nice! Will be testing tomorrow.
