### ISSUE TITLE
Absence of error handling route

### ISSUE THREAD

**Issue by Coteh** [aaronwlee/Attain#9]
In an Express Node.js application I would specify an error handling route like this:
```
app.use(function(err, req, res, next) {
        //error handling stuff here
});
```
and I would expect this to run as the next handler whenever I throw an `Error` in one of my routes. However, this feature doesn't seem to be present in `Attain`. I get the following error upon compilation:
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '(err: any, req: any, res: any, next: any) => void' is not assignable to parameter of type 'string'.ts(2769)
```
I can work around this problem by adding some `try-catch` statements around my code but let me know if there's a better solution I have not thought of. Thanks!

**Comment by aaronwlee** [comment]
@Coteh Thanks for leaving a comment.
I think this is a good feature for error handling. Maybe I'll be going to implement it as soon as possible. 
However, one thing that I'd like to convince is I really don't want to add the next() method for the middlewares. it's inspired by express js but I'd like to make it more Intuitive. I feel it is more clear to understand and build middlewares.

**Comment by devalexqt** [comment]
+1

**Comment by Coteh** [comment]
👍 

You could maybe have a Promise-like system where middlewares that haven't had its response sent invoke the next middleware automatically (resolve path), and middlewares that haven't had its response sent but have instead thrown an error go to the error handling route if it exists (reject path).

**Comment by devalexqt** [comment]
But how to handle error if I throw my custom error in some condition?
For example in my api router:
```
...
router.post("/test",async (req,res)=>{
   ...
If(!req.body.value.data){
throw new Error ("Error, invalid request data.")
}
...
})
```

**Comment by aaronwlee** [comment]
In a current way is using try-catch
```ts
router.post("/test" async (req, res) => {
  try {
    if(!req.params) {
      throw "Params are required";
    }
  } catch (e) {
    console.error(e)
  }
})
```

I envision it to use like this
```ts
router.post("/test" async (req, res) => {
    if(!req.params) {
      throw "Params are required";
    }
})

router.error((error, req, res) => {
   // caught errors and reaching here
   console.error(error);
})
```

or just router.use((error, req, res) => {})

**Comment by devalexqt** [comment]
This will be awesome!
For now:
```
error: Uncaught TypeError: router.error is not a function
router.error((error, req, res) => {
...
```

**Comment by Coteh** [comment]
@aaronwlee I like that solution too! 👍

**Comment by devalexqt** [comment]
May be something like this:
```
app.addEventListener("error",e=>{
  console.log("!!!listener error:",err)
})
```

**Comment by devalexqt** [comment]
Any news how to handle errors?

**Comment by aaronwlee** [comment]
I've done for implementing the error handler.
here is an example code.

```ts
app.use((req, res) => {
  throw new Error("Something wrong!")
})

app.error((error, req, res) => {
  console.error("I handle the Error!" , error);
  res.status(500).send("It's critical!");
})
```

for your information, the error handler is similar to normal middleware. you also can use the path to determine the procedure.

**Comment by devalexqt** [comment]
Tested, look like all working like magic!
Thank you very much!
